config:
  connection:
    credentials:
      tokenURL: https://dev.okta.com/oauth2/abc123/v1/token # URL of the OAuth provider
      user: myUser
      password: '{{ Env "OKTA_PASSWORD" }}'
      scope: okta.myAccount.appAuthenticator.maintenance.manage
    platform: FIREFLY
    trustBundle: /path/to/my/trustbundle.pem # Trust bundle of the Firefly server
    url: https://192.168.1.234:8080 # Firefly server URL
certificateTasks:
  - name: myTask
    renewBefore: 10%
    request:
      csr: service
      keyType: ecdsa
      keyCurve: p256
      sanDNS:
        - my.demo.example
      subject:
        commonName: my.demo.example
      zone: open-source-unrestricted
    installations:
      - format: PEM
        file: "/path/to/my/certificate/cert.cer"
        chainFile: "/path/to/my/certificate/chain.cer"
        keyFile: "/path/to/my/certificate/key.pem"
        afterInstallAction: "echo Success!!!"
